### ISSUE TITLE
> install.packages("rusquant") Warning in install.packages :   package ‘rusquant’ is not available (for R version 3.2.3)

### ISSUE THREAD

**Issue by Djafar1985** [r8m/rusquant#1]
> install.packages("rusquant")
> Warning in install.packages :
>   package ‘rusquant’ is not available (for R version 3.2.3)

how to fix it?

**Comment by r8m** [comment]
If you don't already have devtools installed:
`install.packages("devtools")`

Install my fork version of rusquant:
`library(devtools)`
`install_github("r8m/rusquant")`

**Comment by Djafar1985** [comment]
привет на соседней ветке подсказали, что в CRAN нет этого пакета.
вот он install.packages("rusquant", repos="http://R-Forge.R-project.org", type="source")
вроде поставился, только в библиотеке нет

**Comment by r8m** [comment]
На r-forge главная версия пакета. Одно время авторы  стали редко ее обновлять, и там была одна проблемка с обновлением списка тикеров, если источник данных mfd.ru.  У меня форкнутая версия, где эта проблема решена. 

Если поставился из r-forge, то должно работать.
Попробуй запустить:
`library(rusquant)` 
`getSymbols("SiH6 (03.2016)",from="2016-02-10",period="1min", src="mfd",auto.assign = FALSE)`

**Comment by Djafar1985** [comment]
неа не ставится(((

вчера был, причём дважды качал его с репозитория CRAN: первый раз в предыдущую версию RStudio, а второй в обновлённую. Вечером настраивал рабочее пространство при запуске и прописал в .First разные библиотеки, в которых был в том числе и rusquant. А сегодня запускаю, и он куда-то потерялся. Пробую загрузить - нема.

может проблема в MRO?

**Comment by r8m** [comment]
Может поможет, если  прописать  путь к версии R в R-Studio

**Comment by Djafar1985** [comment]
красавчик! поставилось, спасибо!
у вас такие комплексные огромные библиотеки! прикольно!
а может быть подскажете, как красиво сделать, чтобы все квантовые и трейдинговые библиотеки загружались при старте RStudio? Мне кажется, что 
вызвав через Sys.getenv(“R_HOME”) Rprofile.site и добавив в его функцию .First библиотеки, я сломал всю логику RStudio и все пакеты слетели =))))) и в итоге только сейчас всё удалил и заново поставил. Вроде как работает =)
ещё блин касперский этот достал своими ограничениями =)))

**Comment by Djafar1985** [comment]
Сейчас читаю Гарри https://github.com/hgeorgako/rfortraders, блин как же я запариваюсь по коду, который у меня не работает на машине. Вы не читали его? 
вот моя страничка страданий https://github.com/hgeorgako/rfortraders/issues   =))))
надеюсь, что когда-нибудь (сегодня-завтра), я их осилю =)

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by r8m** [comment]
Можно через проект делать, если я правильно понял. Каждый проект в своей папке со своим workspace'ом.

**Comment by Djafar1985** [comment]
Фига се баг какой! Ваше сообщение 10 раз продублировалось!
Ага понял, спасибо буду пробовать.

**Comment by r8m** [comment]
Упс. С телефона просто отвечал.

**Comment by Djafar1985** [comment]
Спасибо за совет =) сделал библиотеки в проекте. 
Искал, как автоматизировать, нашёл только через Rprofile.site, но чего то там всё ломается после добавления =)))
Вы не знаете, как можно автоматизировать подгрузку библиотек? =)

**Comment by r8m** [comment]
А почему просто нельзя их все вызвать по очереди в скрипте?

**Comment by Djafar1985** [comment]
да да да! я как раз  это и имел ввиду!

**Comment by gBopHuk** [comment]
Чё не так то?
<pre>
> library(devtools)
> install_github("r8m/rusquant")
Downloading GitHub repo r8m/rusquant@master
from URL https://api.github.com/repos/r8m/rusquant/zipball/master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
</pre>
