### ISSUE TITLE
install_github : error in running command

### ISSUE THREAD

**Issue by gBopHuk** [r8m/rusquant#2]
Что ему надо?
<pre>
> library(devtools)
> install_github("r8m/rusquant")
Downloading GitHub repo r8m/rusquant@master
from URL https://api.github.com/repos/r8m/rusquant/zipball/master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
</pre>

**Comment by r8m** [comment]
ОС какая? В Ubuntu была такая проблема в прежних релизах. Попробуйте:
`install_git('https://github.com/r8m/rusquant.git')`

**Comment by gBopHuk** [comment]
Спасибо за совет!
На данный момент ALTLlinux/Sisyphus ( testing в терминах debian/ubuntu,  тот который в режиме rolling release ) пакет удалось скачать  командой
  install_git('https://github.com/r8m/rusquant.git')

На текущем stable ALTLinux/p8 всё установилось командой
  install_github("r8m/rusquant").
