### ISSUE TITLE
loadStockListMoex(market=c("MOEX", "FORTS"))

### ISSUE THREAD

**Issue by gBopHuk** [r8m/rusquant#3]
loadStockListMoex(market=c("MOEX", "FORTS"))
trying URL 'http://www.moex.com/iss/rms/engines/stock/objects/marketrates.csv?iss.only=object&limit=unlimited&sort_column=SECID&sort_order=ASC&security_types=common_share,preferred_share,depositary_receipt,ofz_bond,cb_bond,subfederal_bond,municipal_bond,corporate_bond,exchange_bond,ifi_bond,euro_bond,public_ppif,interval_ppif,private_ppif,stock_mortgage,etf_ppif&board_groups=stock_tplus,stock_ndm_tplus,stock_small_tplus,stock_qnv_tplus,stock_ndm_qnv_tplus,stock_d_tplus,stock_d_ndm_tplus,stock_t0,stock_ndm,stock_qnv,stock_ndm_qnv,stock_d_ndm,stock_bonds_d_main,stock_bonds_d_ndm,stock_darkpool,stock_b_spob,stock_b_psau,stock_b_auct,stock_b_psbb,stock_b_aubb,stock_repo_na,stock_repo_adr,stock_repo_shares,stock_repo_bonds,stock_repo_qnv&index=&listname=1,2,3,_&collateral=0&currencyid=&lang=ru'
Content type 'text/csv; charset=windows-1251' length unknown
.......... .......... .......... .......... ..........
.......... .......... .......... .......... .
downloaded 91 KB

trying URL 'ftp://ftp.moex.com/pub/info/stats/forts/FORTS_LIST.TXT'
ftp data connection made, file length unknown
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... 
downloaded 2.2 MB

Error in type.convert(data[[i]], as.is = as.is[i], dec = dec, numerals = numerals,  : 
  invalid multibyte string at '<d4><fc><fe><f7><e5><f0><f1><ed><fb><e9><20><ea><ee><ed><f2><f0><e0><ea><f2><20><ed><e0><20><ee><e1><fb><ea><ed><ee><e2><e5><ed><ed><fb><e5><20><e0><ea><f6><e8><e8><20><c0><ca><20><22><c0><cb><d0><ce><d1><c0><22><20><28><cf><c0><ce><29>'

**Comment by r8m** [comment]
Пофиксил для фортса, перзагрузите пакет.  Для фонды возвращает нулевой датафрейм. Позже посмотрю.

**Comment by gBopHuk** [comment]
ошибки нет 

<pre>
loadStockListMoex(market=c("MOEX", "FORTS"))
[...]
[1] shortSymbol             shortName               FORTSlist.short_name_en
 [4] FORTSlist.symbol        type                    FORTSlist.contract_type
 [7] deliveryDate            FORTSlist.strike_price  FORTSlist.amount       
[10] FORTSlist.option_type  
<0 rows> (or 0-length row.names)
</pre>
Но что я получил - не понятно : 
<pre>
> ls()
[1] "finam.stock.list" "from"             "to"  
</pre>

Как этим пользоваться ? Где stocklist с moex?

**Comment by r8m** [comment]
Пока никак. Эта функция нужна была для сопоставления  имен тикеров с базой mfd.

**Comment by gBopHuk** [comment]
Просто было интересно что она делает в примере на главной странице? Значит пока ничего! Тогда закрываю задачу
